language: bash

branches:
  only:
  - master

os:
  - linux
  - osx

before_install:
- if [`uname` = "Linux"]; then
    sudo apt-get update -qq;
    sudo apt-get install -qq ansible;
    sudo mv builds/corr-storage /corr-storage;
    sudo mkdir /corr-src;
    sudo mkdir /corr-src/corr;
  elif [`uname` = "Darwin"]; then
    bundle install;
    brew update;
    brew install ansible;
    sudo mkdir /corr-src;
    sudo mkdir /corr-src/corr;
  fi

script:
- if [`uname` = "Linux"]; then
    sudo ./native/config.bash --ask-sudo --tags install --inventory-file native/builds/hosts.travis;
  elif [`uname` = "Darwin"]; then
    sudo ./docker/ansible-docker.bash --ask-sudo --tags install --inventory-file docker/hosts.travis;
    sudo mv builds/corr-storage /corr-storage;
    sudo mv builds/data /data;
  fi
