- stat: path=./builds
  register: build_folder

- name: create builds folder
  file: path=./builds state=directory
  when: build_folder.stat.exists == False

- name: remove aws
  shell: rm -rf ./builds/aws
  when: >
    inventory_hostname in groups['api'] or
    inventory_hostname in groups['cloud'] and
    build_folder.stat.exists == True

- name: remove src
  shell: rm -rf ./builds/corr
  when: build_folder.stat.exists == True

- name: remove db config
  shell: rm -rf ./builds/mongodb.conf
  when: inventory_hostname in groups['db']

- name: remove requirements
  shell: rm -rf ./builds/requirements.yaml
  when: >
    inventory_hostname in groups['db'] and
    inventory_hostname in groups['api'] and
    inventory_hostname in groups['cloud'] and
    inventory_hostname in groups['frontend'] and
    build_folder.stat.exists == True

- name: remove Dockerfile Db
  shell: rm -rf ./builds/Dockerfile-db
  when: >
    inventory_hostname in groups['db'] and
    build_folder.stat.exists == True

- name: remove Dockerfile Api
  shell: rm -rf ./builds/Dockerfile-api
  when: >
    inventory_hostname in groups['api'] and
    build_folder.stat.exists == True

- name: remove Dockerfile Cloud
  shell: rm -rf ./builds/Dockerfile-cloud
  when: >
    inventory_hostname in groups['cloud'] and
    build_folder.stat.exists == True

- name: remove Dockerfile Frontend
  shell: rm -rf ./builds/Dockerfile-frontend
  when: >
    inventory_hostname in groups['frontend'] and
    build_folder.stat.exists == True