version: '2'
services:
  # CoRR MongoDB database container.
  corrdb:
    build:
        context: ./builds
        dockerfile: Dockerfile-db
    ports:
     - "27017:27017"
    expose:
     - "27017"
    volumes:
     # Location of the Mongodb database folder.
     # Make sure a db folder is in it.
     # Ubuntu
     # - /var/lib/mongodb:/data/db
     # MacOSX
     - /Users/fyc/vbox/data:/data
  # CoRR API service container.
  corrapi:
    build:
        context: ./builds
        dockerfile: Dockerfile-api
    ports:
     - "5100:5100"
    volumes:
     # Location of the file system storage.
     # Ubuntu
     # - /corr-storage:/home/corradmin/corr-storage
     # MacOSX
     - /Users/fyc/vbox/corr-storage:/home/corradmin/corr-storage
    depends_on:
     - "corrdb"
  # CoRR Cloud service container.
  corrcloud:
    build:
        context: ./builds
        dockerfile: Dockerfile-cloud
    ports:
     - "5200:5200"
    volumes:
     # Locations of the file system storage
     # and the admin configuration file folder: /tmp/tmp_admin.json
     # Ubuntu
     # - /corr-storage:/home/corradmin/corr-storage
     # MacOSX
     - /Users/fyc/vbox/corr-storage:/home/corradmin/corr-storage
     - /Users/fyc/vbox/tmp:/tmp
    expose:
     - "5200"
    depends_on:
     - "corrdb"
  # CoRR Frontend service container.
  corrview:
    build:
        context: ./builds
        dockerfile: Dockerfile-frontend
    ports:
     - "5000:5000"
    depends_on:
     - "corrcloud"
