- name: restart the db container
  when: inventory_hostname in groups['db']
  shell: /home/{{ ansible_ssh_user }}/{{ anacondadir }}/envs/{{ corr_env }}/bin/docker-compose restart -t 20 corrdb
  become: true

- name: wait for mongodb to become available
  when: >
    inventory_hostname in groups['api'] or
    inventory_hostname in groups['cloud']
  wait_for:
    port: 27017

- name: restart the api container
  when: inventory_hostname in groups['api']
  shell: /home/{{ ansible_ssh_user }}/{{ anacondadir }}/envs/{{ corr_env }}/bin/docker-compose restart -t 20 corrapi
  become: true

- name: restart the cloud container
  when: inventory_hostname in groups['cloud']
  shell: /home/{{ ansible_ssh_user }}/{{ anacondadir }}/envs/{{ corr_env }}/bin/docker-compose restart -t 20 corrcloud
  become: true

- name: restart the frontend container
  when: inventory_hostname in groups['frontend']
  shell: /home/{{ ansible_ssh_user }}/{{ anacondadir }}/envs/{{ corr_env }}/bin/docker-compose restart -t 20 corrview
  become: true