- name: shuting down db container
  when: inventory_hostname in groups['db']
  shell: /home/{{ ansible_ssh_user }}/{{ anacondadir }}/envs/{{ corr_env }}/bin/docker-compose stop corrdb
  become: true
  register: output

- name: shuting down api container
  when: inventory_hostname in groups['api']
  shell: /home/{{ ansible_ssh_user }}/{{ anacondadir }}/envs/{{ corr_env }}/bin/docker-compose stop corrapi
  become: true
  register: output

- name: shuting down cloud container
  when: inventory_hostname in groups['cloud']
  shell: /home/{{ ansible_ssh_user }}/{{ anacondadir }}/envs/{{ corr_env }}/bin/docker-compose stop corrcloud
  become: true
  register: output

- name: shuting down frontend container
  when: inventory_hostname in groups['frontend']
  shell: /home/{{ ansible_ssh_user }}/{{ anacondadir }}/envs/{{ corr_env }}/bin/docker-compose stop corrview
  become: true
  register: output